---

include:
  - { project: gitlab/ci-templates, file: build/docker.yml }
  - { project: gitlab/ci-templates, file: release/semantic.yml }
  - { project: gitlab/ci-templates, file: release/github.yml }
  - { project: gitlab/ci-templates, file: release/dockerhub.yml }

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_MESSAGE =~ /chore\(release\):/
      when: never
    - if: $CI_PIPELINE_SOURCE =~ /api|push|merge|web/

stages:
  - build
  - release
