---
name: pr

on:
  pull_request

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: build --snapshot --rm-dist --single-target
  helm-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dtzar/helm-kubectl:3.8.2
    steps:
      - uses: actions/checkout@v3
      - run: helm lint deploy/cert-manager-webhook-autodns
