---
name: pr

on:
  pull_request

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: build --snapshot --rm-dist --single-target
