---
name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          registry: r.planetary-quantum.com
          username: ${{ secrets.QUANTUM_REGISTRY_USERNAME }}
          password: ${{ secrets.QUANTUM_REGISTRY_PASSWORD }}
      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  helm:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dtzar/helm-kubectl:3.8.2
    steps:
      - uses: actions/checkout@v3
      - run: helm plugin install https://github.com/chartmuseum/helm-push.git
      - name: "Add chart repo (r.planetary-quantum.com)"
        run: >
          helm repo add
          runway-public https://r.planetary-quantum.com/chartrepo/runway-public
      - run: helm search repo runway-public
      - run: >
          helm cm-push 
          --username '${{ secrets.QUANTUM_REGISTRY_USERNAME }}'
          --password '${{ secrets.QUANTUM_REGISTRY_PASSWORD }}'
          deploy/cert-manager-webhook-autodns
          runway-public
